### ISSUE TITLE
KeyError: 'eid'

### ISSUE THREAD

**Issue by CNJasonChio** [Rlacat/jd-automask#12]
简洁模式已开启
6_309_311_39393
2020-02-10 00:30:12,580 INFO: [106]个需要检测的商品
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: 'eid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasonchio/Desktop/jd-automask-master/jd-automask_V1.py", line 71, in <module>
    eid = global_config.getRaw('config', 'eid')
  File "/Users/jasonchio/Desktop/jd-automask-master/config/config.py", line 20, in getRaw
    return self._configRaw.get(section, name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'eid' in section: 'config'
(base) zhaoyaoangdeAir:jd-automask-master jasonchio$

**Comment by skbeh** [comment]
+1

**Comment by yangzelong14** [comment]
怎么解决呀

**Comment by hnliuzesen** [comment]
> 怎么解决呀

文本编辑 jd-automask-V1.py ，第71、72行，删掉
