### ISSUE TITLE
EXE闪退问题解决办法

### ISSUE THREAD

**Issue by zhyreng** [Rlacat/jd-automask#18]
将文件jd-automask_V2.py中46行的ua = UserAgent()改为：ua = UserAgent(verify_ssl=False)

**Comment by Rlacat** [comment]
试过了，解决不了。
只能把模拟ua去掉了

**Comment by zhyreng** [comment]
可以呀，我跑起来了

**Comment by zhyreng** [comment]
跑一段时间不行是因为连接拒绝，看来10个线程也太频繁

**Comment by zhyreng** [comment]
Traceback (most recent call last):
  File "D:/Person/JD/jdmask_a1 _code/jd-automask_V2.py", line 829, in validate_cookies
    resp = session.get(url=targetURL, params=payload, allow_redirects=False)
  File "D:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('### Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by zhyreng** [comment]
其实感觉不用模拟ua，采用原作者的v3多线程就好了，每个线程一个cookie。
