### ISSUE TITLE
Eid 报错的问题怎么解决啊？

### ISSUE THREAD

**Issue by 13129761422** [Rlacat/jd-automask#20]
2020-02-12 11:18:11,468 INFO: [106]个需要检测的商品
Traceback (most recent call last):
  File "D:\path\python3.7\lib\configparser.py", line 788, in get
    value = d[option]
  File "D:\path\python3.7\lib\collections\__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "D:\path\python3.7\lib\collections\__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'eid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/lrz/Downloads/jd-automask-master/jd-automask-master/jd-automask_V1.py", line 71, in <module>
    eid = global_config.getRaw('config', 'eid')
  File "C:\Users\lrz\Downloads\jd-automask-master\jd-automask-master\config\config.py", line 20, in getRaw
    return self._configRaw.get(section, name)
  File "D:\path\python3.7\lib\configparser.py", line 791, in get
简洁模式已开启
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'eid' in section: 'config'
19_1690_1693_39745

Process finished with exit code 1

**Comment by 1229984599** [comment]
config.ini里面定义eid和fp为空就可以了，作者已经把这两个字段给注释掉了，但是在读取配置的时候忘了删了
