### ISSUE TITLE
exe打开报错后闪退

### ISSUE THREAD

**Issue by Malloc-001** [Rlacat/jd-automask#23]
Traceback (most recent call last):
  File "jd-automask_V2.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "message\message.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "config\config.py", line 23, in <module>
  File "config\config.py", line 12, in __init__
  File "configparser.py", line 696, in read
  File "configparser.py", line 1079, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'E:\\BaiduNetdiskDownload\\jdmask_a1\\config.ini', line: 1
'\ufeff[config]\n'
[16264] Failed to execute script jd-automask_V2

**Comment by fanxlxs** [comment]
我的也会闪退   但是我截不到错误代码

**Comment by kingmanyun** [comment]
config.ini编码格式导致。请使用字符编辑软件重新保存 config.ini文件，需要保存为UTF-8无BOM格式才可以

**Comment by fanxlxs** [comment]
可以了

**Comment by eternally1970** [comment]
> config.ini编码格式导致。请使用字符编辑软件重新保存 config.ini文件，需要保存为UTF-8无BOM格式才可以
感谢，已经可以了
