### ISSUE TITLE
报错，无法下单

### ISSUE THREAD

**Issue by PRSJMC** [Rlacat/jd-automask#25]
报错代码如下：
`2020-02-14 15:33:55,652 INFO: [7296030]类型口罩有货啦!马上下单
2020-02-14 15:33:55,653 INFO: 第[1/3]次尝试提交订单
2020-02-14 15:33:56,208 INFO: 购物车信息：{}
2020-02-14 15:33:56,525 ERROR: 7296030 添加到购物车失败
2020-02-14 15:33:59,133 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
Exception in thread item_exist_7296030:
Traceback (most recent call last):
  File "C:\Users\JMC-Per1recover\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "jd-automask_V1.py", line 761, in run
    is_item_removed(self.skuid)
  File "jd-automask_V1.py", line 795, in is_item_removed
    if buyMask(skuId):
  File "jd-automask_V1.py", line 480, in buyMask
    risk_control = get_checkout_page_detail()
  File "jd-automask_V1.py", line 363, in get_checkout_page_detail
    return risk_control
UnboundLocalError: local variable 'risk_control' referenced before assignment
Traceback (most recent call last):
  File "jd-automask_V1.py", line 822, in <module>
    auto_buy(inStockSkuid)
  File "jd-automask_V1.py", line 777, in auto_buy
    threads[j].join()   #循环 join()方法可以让主线程等待所有的线程都执行完毕。
  File "C:\Users\JMC-Per1recover\AppData\Local\Programs\Python\Python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "C:\Users\JMC-Per1recover\AppData\Local\Programs\Python\Python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt`

**Comment by 3gZ2jA** [comment]
同不能下单，一样的错误
