### ISSUE TITLE
Exceeded 30 redirects.又出现了，53056247241是用来验证的有货的商品的id

### ISSUE THREAD

**Issue by c0ldian** [Rlacat/jd-automask#6]
2020-02-08 22:47:22,874 INFO: [21]个需要检测的商品
2020-02-08 22:47:23,937 INFO: 登录账号名称
2020-02-08 22:47:24,141 INFO: 第2次检测结束.耗时： 0s
2020-02-08 22:47:24,537 INFO: [53056247241]类型口罩有货啦!马上下单
2020-02-08 22:47:24,537 INFO: 第[1/3]次尝试提交订单
2020-02-08 22:47:24,762 INFO: [53056247241]类型口罩有货啦!马上下单
2020-02-08 22:47:24,763 INFO: 第[1/3]次尝试提交订单
2020-02-08 22:47:25,114 INFO: 购物车信息：{}
2020-02-08 22:47:25,432 INFO: 购物车信息：{}
2020-02-08 22:47:25,805 INFO: 53056247241  已成功加入购物车
2020-02-08 22:47:26,089 INFO: 53056247241  已成功加入购物车
2020-02-08 22:47:29,309 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-08 22:47:29,505 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-08 22:47:29,513 INFO: 第3次检测结束.耗时： 5s
2020-02-08 22:47:29,893 INFO: 第4次检测结束.耗时： 0s
2020-02-08 22:47:30,345 INFO: [53056247241]类型口罩有货啦!马上下单
2020-02-08 22:47:30,346 INFO: 第[1/3]次尝试提交订单
2020-02-08 22:47:30,614 INFO: [53056247241]类型口罩有货啦!马上下单
2020-02-08 22:47:30,615 INFO: 第[1/3]次尝试提交订单
2020-02-08 22:47:31,115 INFO: 购物车信息：{'53056247241': {'name': '汤老鸭百瑞福鸭脖鸭心鸭肝鸭翅鸭腿锁骨鹌鹑蛋卤味熟食小包装休闲香辣即食零食 鸭心 （老汤香辣 16g*30袋）', 'verder_id': '10203828', 'count': 2, 'unit_price': '29.90', 'total_price': '59.80', 'is_selected': False, 'p_type': '11', 'target_id': '33542998074', 'promo_id': '33542998074'}}
2020-02-08 22:47:31,116 INFO: 53056247241 已在购物车中，调整数量为 1
2020-02-08 22:47:31,394 INFO: 购物车信息：{'53056247241': {'name': '汤老鸭百瑞福鸭脖鸭心鸭肝鸭翅鸭腿锁骨鹌鹑蛋卤味熟食小包装休闲香辣即食零食 鸭心 （老汤香辣 16g*30袋）', 'verder_id': '10203828', 'count': 2, 'unit_price': '29.90', 'total_price': '59.80', 'is_selected': False, 'p_type': '11', 'target_id': '33542998074', 'promo_id': '33542998074'}}
2020-02-08 22:47:31,395 INFO: 53056247241 已在购物车中，调整数量为 1
2020-02-08 22:47:34,703 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-08 22:47:34,983 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-08 22:47:34,994 INFO: 第5次检测结束.耗时： 5s
2020-02-08 22:47:35,351 INFO: 第6次检测结束.耗时： 0s
2020-02-08 22:47:35,801 INFO: [53056247241]类型口罩有货啦!马上下单
2020-02-08 22:47:35,801 INFO: 第[1/3]次尝试提交订单
2020-02-08 22:47:36,206 INFO: [53056247241]类型口罩有货啦!马上下单
2020-02-08 22:47:36,206 INFO: 第[1/3]次尝试提交订单
2020-02-08 22:47:36,642 INFO: 购物车信息：{'53056247241': {'name': '汤老鸭百瑞福鸭脖鸭心鸭肝鸭翅鸭腿锁骨鹌鹑蛋卤味熟食小包装休闲香辣即食零食 鸭心 （老汤香辣 16g*30袋）', 'verder_id': '10203828', 'count': 1, 'unit_price': '29.90', 'total_price': '29.90', 'is_selected': False, 'p_type': '11', 'target_id': '33542998074', 'promo_id': '33542998074'}}
2020-02-08 22:47:36,643 INFO: 53056247241 已在购物车中，调整数量为 1
2020-02-08 22:47:36,998 INFO: 购物车信息：{'53056247241': {'name': '汤老鸭百瑞福鸭脖鸭心鸭肝鸭翅鸭腿锁骨鹌鹑蛋卤味熟食小包装休闲香辣即食零食 鸭心 （老汤香辣 16g*30袋）', 'verder_id': '10203828', 'count': 1, 'unit_price': '29.90', 'total_price': '29.90', 'is_selected': False, 'p_type': '11', 'target_id': '33542998074', 'promo_id': '33542998074'}}
2020-02-08 22:47:36,999 INFO: 53056247241 已在购物车中，调整数量为 1
2020-02-08 22:47:40,179 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-08 22:47:40,628 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.

**Comment by tangli159** [comment]
同，我也出现了一样的问题。

**Comment by diaomina** [comment]
同样的问题，log如下：

2020-02-09 00:47:52,223 INFO: 第[1/3]次尝试提交订单
2020-02-09 00:47:53,223 INFO: 购物车信息：{'63900512280': {'name': '红珍 山楂蜜卷散装200g 果丹皮山楂卷 山楂蜜饯果脯儿童零食小吃 河北特产 山楂蜜卷200g', 'verder_id': '10237326', 'count': 1, 'unit_price': '9.90', 'total_price': '9.90', 'is_selected': False, 'p_type': '1', 'target_id': 0, 'promo_id': 0}}
2020-02-09 00:47:53,224 INFO: 63900512280 已在购物车中，调整数量为 1
2020-02-09 00:47:57,601 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-09 00:47:59,654 INFO: 第3次检测结束.耗时： 8s
2020-02-09 00:48:01,104 INFO: [63900512280]类型口罩有货啦!马上下单
2020-02-09 00:48:01,104 INFO: 第[1/3]次尝试提交订单
2020-02-09 00:48:01,931 INFO: 购物车信息：{'63900512280': {'name': '红珍 山楂蜜卷散装200g 果丹皮山楂卷 山楂蜜饯果脯儿童零食小吃 河北特产 山楂蜜卷200g', 'verder_id': '10237326', 'count': 1, 'unit_price': '9.90', 'total_price': '9.90', 'is_selected': False, 'p_type': '1', 'target_id': 0, 'promo_id': 0}}
2020-02-09 00:48:01,931 INFO: 63900512280 已在购物车中，调整数量为 1
2020-02-09 00:48:10,184 INFO: [116]个需要检测的商品
2020-02-09 00:48:17,316 INFO: 登录账号名称
2020-02-09 00:48:18,811 INFO: [63900512280]类型口罩有货啦!马上下单
2020-02-09 00:48:18,812 INFO: 第[1/3]次尝试提交订单
2020-02-09 00:48:19,560 INFO: 购物车信息：{}
2020-02-09 00:48:20,319 INFO: 63900512280  已成功加入购物车
2020-02-09 00:48:24,436 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-09 00:48:26,549 INFO: 第2次检测结束.耗时： 9s

**Comment by willyu320** [comment]
猛男流泪 为什么会这样
2020-02-09 03:19:04,966 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
Exception in thread item_exist_1798191:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "jd-automask_V1.py", line 760, in run
  File "jd-automask_V1.py", line 794, in is_item_removed
  File "jd-automask_V1.py", line 479, in buyMask
  File "jd-automask_V1.py", line 362, in get_checkout_page_detail
UnboundLocalError: local variable 'risk_control' referenced before assignment

**Comment by 13211222** [comment]
重复把cookie删了登陆几次，我就是这样搞定的

**Comment by c0ldian** [comment]
> 重复把cookie删了登陆几次，我就是这样搞定的

怎么操作，直接删cookie，然后扫码登陆就好了吗？具体重复几次呢

**Comment by 13211222** [comment]
> > 重复把cookie删了登陆几次，我就是这样搞定的
> 
> 怎么操作，直接删cookie，然后扫码登陆就好了吗？具体重复几次呢
对的，我昨晚重复三次左右，然后没事的时候又重复了三次，要睡觉的时候也重复三次，我也不知道什么原因，只能是相信软件，昨晚就抢到了口罩，今天继续 #8

**Comment by c0ldian** [comment]
> > > 重复把cookie删了登陆几次，我就是这样搞定的
> > 
> > 
> > 怎么操作，直接删cookie，然后扫码登陆就好了吗？具体重复几次呢
> > 对的，我昨晚重复三次左右，然后没事的时候又重复了三次，要睡觉的时候也重复三次，我也不知道什么原因，只能是相信软件，昨晚就抢到了口罩，今天继续 #8

看了一下另一边的评论，好像是扫码的cookie容易失效导致的

**Comment by diaomina** [comment]
亲测删除cookie重新扫码登录后不会出现该错误

**Comment by c0ldian** [comment]
> 亲测删除cookie重新扫码登录后不会出现该错误

吼

**Comment by Rlacat** [comment]
可能是瞬时发送的id过多 或者被反爬虫 目前更新后没出现这个状况
