### ISSUE TITLE
这究竟是为什么啊ERROR: 订单结算页面获取异常：Exceeded 30 redirects.

### ISSUE THREAD

**Issue by willyu320** [Rlacat/jd-automask#7]
Sun Feb  9 03:22:51 2020 > 检查登录状态中...
登陆状态正常
2020-02-09 03:22:54,739 INFO: 登录账号名称
2020-02-09 03:22:55,582 INFO: []类型口罩无货
2020-02-09 03:22:55,598 INFO: 第2次检测结束.耗时： 0s
2020-02-09 03:22:57,488 INFO: []类型口罩无货
2020-02-09 03:22:57,520 INFO: 第3次检测结束.耗时： 1s
2020-02-09 03:22:58,004 INFO: [1798191]类型口罩有货啦!马上下单
2020-02-09 03:22:58,004 INFO: 第[1/3]次尝试提交订单
2020-02-09 03:22:58,394 INFO: []类型口罩无货
2020-02-09 03:22:58,427 INFO: 第4次检测结束.耗时： 0s
2020-02-09 03:22:58,769 INFO: [1798191]类型口罩有货啦!马上下单
2020-02-09 03:22:58,769 INFO: 第[1/3]次尝试提交订单
2020-02-09 03:22:58,988 INFO: []类型口罩无货
2020-02-09 03:22:59,005 INFO: 第5次检测结束.耗时： 0s
2020-02-09 03:22:59,113 INFO: 购物车信息：{}
2020-02-09 03:22:59,238 INFO: [1798191]类型口罩有货啦!马上下单
2020-02-09 03:22:59,238 INFO: 第[1/3]次尝试提交订单
2020-02-09 03:22:59,988 INFO: 购物车信息：{}
2020-02-09 03:23:00,238 INFO: 1798191  已成功加入购物车
2020-02-09 03:23:00,426 INFO: []类型口罩无货
###[等待]已到达配置最大进程数[5]###
2020-02-09 03:23:00,879 INFO: [1798191]类型口罩有货啦!马上下单
2020-02-09 03:23:00,879 INFO: 第[1/3]次尝试提交订单
2020-02-09 03:23:01,191 INFO: 1798191  已成功加入购物车
2020-02-09 03:23:02,552 INFO: 购物车信息：{'1798191': {'name': '益达木糖醇无糖口香糖大瓶装混合味70粒98g单瓶装（新旧包装 随机发）零食糖果休闲食品', 'verder_id': '8888', 'count': 1, 'unit_price': '12.90', 'total_price': '12.90', 'is_selected': False, 'p_type': '11', 'target_id': '50073326400', 'promo_id': '50073326400'}}
2020-02-09 03:23:02,552 INFO: 1798191 已在购物车中，调整数量为 1
2020-02-09 03:23:02,597 INFO: 购物车信息：{'1798191': {'name': '益达木糖醇无糖口香糖大瓶装混合味70粒98g单瓶装（新旧包装 随机发）零食糖果休闲食品', 'verder_id': '8888', 'count': 1, 'unit_price': '12.90', 'total_price': '12.90', 'is_selected': False, 'p_type': '11', 'target_id': '50073326400', 'promo_id': '50073326400'}}
2020-02-09 03:23:02,597 INFO: 1798191 已在购物车中，调整数量为 1
2020-02-09 03:23:03,316 INFO: [1798191]类型口罩有货啦!马上下单
2020-02-09 03:23:12,478 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-09 03:23:12,634 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-09 03:23:14,713 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-09 03:23:15,228 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
2020-02-09 03:23:21,556 INFO: 第[1/3]次尝试提交订单
Exception in thread item_exist_1798191:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "jd-automask_V1.py", line 760, in run
  File "jd-automask_V1.py", line 794, in is_item_removed
  File "jd-automask_V1.py", line 479, in buyMask
  File "jd-automask_V1.py", line 362, in get_checkout_page_detail
UnboundLocalError: local variable 'risk_control' referenced before assignment

Exception in thread item_exist_1798191:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "jd-automask_V1.py", line 760, in run
  File "jd-automask_V1.py", line 794, in is_item_removed
  File "jd-automask_V1.py", line 479, in buyMask
  File "jd-automask_V1.py", line 362, in get_checkout_page_detail
UnboundLocalError: local variable 'risk_control' referenced before assignment
Exception in thread item_exist_1798191:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "jd-automask_V1.py", line 760, in run
  File "jd-automask_V1.py", line 794, in is_item_removed
  File "jd-automask_V1.py", line 479, in buyMask
  File "jd-automask_V1.py", line 362, in get_checkout_page_detail
UnboundLocalError: local variable 'risk_control' referenced before assignment
Exception in thread item_exist_1798191:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "jd-automask_V1.py", line 760, in run
  File "jd-automask_V1.py", line 794, in is_item_removed
  File "jd-automask_V1.py", line 479, in buyMask
  File "jd-automask_V1.py", line 362, in get_checkout_page_detail
UnboundLocalError: local variable 'risk_control' referenced before assignment

2020-02-09 03:23:22,056 INFO: 购物车信息：{'1798191': {'name': '益达木糖醇无糖口香糖大瓶装混合味70粒98g单瓶装（新旧包装 随机发）零食糖果休闲食品', 'verder_id': '8888', 'count': 1, 'unit_price': '12.90', 'total_price': '12.90', 'is_selected': False, 'p_type': '11', 'target_id': '50073326400', 'promo_id': '50073326400'}}
2020-02-09 03:23:22,056 INFO: 1798191 已在购物车中，调整数量为 1
2020-02-09 03:23:35,775 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
Exception in thread item_exist_1798191:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "jd-automask_V1.py", line 760, in run
  File "jd-automask_V1.py", line 794, in is_item_removed
  File "jd-automask_V1.py", line 479, in buyMask
  File "jd-automask_V1.py", line 362, in get_checkout_page_detail
UnboundLocalError: local variable 'risk_control' referenced before assignment

**Comment by diaomina** [comment]
删除cookie，重新扫码登录后不会出现该错误
