### ISSUE TITLE
2020-02-09 12:26:09,450 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.

### ISSUE THREAD

**Issue by jocket1314** [Rlacat/jd-automask#9]
2020-02-09 12:26:27,163 INFO: 第8次检测结束.耗时： 11s
2020-02-09 12:26:28,729 INFO: [100005603522]类型口罩有货啦!马上下单
2020-02-09 12:26:28,741 INFO: 第[1/3]次尝试提交订单
2020-02-09 12:26:30,219 INFO: 购物车信息：{'100005603522': {'name': '荣耀20 李现同款 4800万超广角AI四摄 3200W美颜自拍 麒麟Kirin980全网通版8GB+128GB 幻夜黑 全面屏手机', 'verder_id': '8888', 'count': 1, 'unit_price': '2089.00', 'total_price': '2089.00', 'is_selected': False, 'p_type': '13', 'target_id': '50066850873', 'promo_id': '50066850873'}}
2020-02-09 12:26:30,221 INFO: 100005603522 已在购物车中，调整数量为 1
2020-02-09 12:26:34,486 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
Exception in thread item_exist_100005603522:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "jd-automask_V1.py", line 760, in run
  File "jd-automask_V1.py", line 794, in is_item_removed
  File "jd-automask_V1.py", line 479, in buyMask
  File "jd-automask_V1.py", line 362, in get_checkout_page_detail
UnboundLocalError: local variable 'risk_control' referenced before assignment

失败了，这个获取异常怎么处理

**Comment by diaomina** [comment]
亲测删除cookie重新扫码登录后不会出现该错误

**Comment by diaomina** [comment]
> 2020-02-09 12:26:27,163 INFO: 第8次检测结束.耗时： 11s
> 2020-02-09 12:26:28,729 INFO: [100005603522]类型口罩有货啦!马上下单
> 2020-02-09 12:26:28,741 INFO: 第[1/3]次尝试提交订单
> 2020-02-09 12:26:30,219 INFO: 购物车信息：{'100005603522': {'name': '荣耀20 李现同款 4800万超广角AI四摄 3200W美颜自拍 麒麟Kirin980全网通版8GB+128GB 幻夜黑 全面屏手机', 'verder_id': '8888', 'count': 1, 'unit_price': '2089.00', 'total_price': '2089.00', 'is_selected': False, 'p_type': '13', 'target_id': '50066850873', 'promo_id': '50066850873'}}
> 2020-02-09 12:26:30,221 INFO: 100005603522 已在购物车中，调整数量为 1
> 2020-02-09 12:26:34,486 ERROR: 订单结算页面获取异常：Exceeded 30 redirects.
> Exception in thread item_exist_100005603522:
> Traceback (most recent call last):
> File "threading.py", line 917, in _bootstrap_inner
> File "jd-automask_V1.py", line 760, in run
> File "jd-automask_V1.py", line 794, in is_item_removed
> File "jd-automask_V1.py", line 479, in buyMask
> File "jd-automask_V1.py", line 362, in get_checkout_page_detail
> UnboundLocalError: local variable 'risk_control' referenced before assignment
> 
> 失败了，这个获取异常怎么处理
亲测删除cookie重新扫码登录后不会出现该错误

**Comment by solife2020** [comment]
应该给出一个窗口显示购买成功的信息。

**Comment by nxtjy** [comment]
每次退出再打开自动登录后，都有这个问题，建议每次登录时强制扫描二维码
